kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner-role
rules:
  - verbs:
      - create
      - update
      - delete
      - patch
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - '*'
