kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-gitlab-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gitlab-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-gitlab
